version: '3.3'
services:
  postgres:
    image: postgres:latest
    container_name: postgres_microservices
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root2024
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d/
volumes:
  postgres_data:
